---
title: "sandbox"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(scales)
library(lubridate)
```

```{r simulate_user_traffic}
# unique daily visits e.g. 1 record means that the person may have visited the site 1+ times for that day (the number of times does not matter)
# what is the distribution of returning visitors? i.e. how many unique days will most people visit the website?

# 20K visits users per month, over 10 months
total_visits_per_unique_data <- 100000
#return_visit
#user_traffic
#set.seed(42)
ids <- floor(runif(total_visits_per_unique_data, min=1, max=total_visits_per_unique_data * 0.50))
num_unique_ids <- length(unique(ids))

visits <- data.frame(user_id=ids) %>%
    arrange(user_id)

visits %>%
    count(user_id) %>%
    count(n) %>%
    mutate(n=factor(n),
           nn=nn / num_unique_ids) %>%
    rename(unique_days_visited=n,
           number_of_ids=nn) %>%
    ggplot(aes(x=unique_days_visited, y=number_of_ids)) +
        geom_col() +
        geom_text(aes(label=percent(number_of_ids)), vjust=-0.3)
```

```{r traffic_2}
# simulate dates over last e.g 10 months
# we need to duplicate ids/days to simulate people visiting multiple paths per day; we'll use this information for our priors
number_of_months <- 10

# unique visitors per month
num_unique_ids / number_of_months

#set.seed(42)
first_time_visit_index <- floor(runif(num_unique_ids, min=0, max=300))

# create dataframe with the user-id and the offset that we will use from the current date
# we'll use the current date so we can simulate the latest experiment is currently running 
first_time_users <- data.frame(user_id=unique(ids), visit_offset=first_time_visit_index) %>% 
    arrange(user_id)

first_time_users <- first_time_users %>%
    mutate(first_visit_date=today() - visit_offset) %>%
    select(-visit_offset)

first_time_users %>%
    count(first_visit_date) %>%
    ggplot(aes(x=first_visit_date, y=n)) +
        geom_line() +
        expand_limits(y=0) +
        labs(title='Simulated Daily Visits, no trend')

visits <- inner_join(visits, first_time_users, by = 'user_id')

stopifnot(nrow(visits) == length(ids))
stopifnot(all((visits %>%
    group_by(user_id) %>%
    summarise(num_unique_date=length(unique(first_visit_date))))$num_unique_date == 1))

# now simulate adding number of days between subsequent visits
hist(rgamma(1000, shape=4))


visits <- visits %>%
    group_by(user_id) %>%
    mutate(visit_index = row_number()) %>%
    ungroup()

generate_new_date <- function(visit_index, original_date, user_id) {

    if(visit_index == 1) {
        return (original_date)
    }
    
    #set.seed(user_id)
    offset <- floor(rgamma(1, shape=visit_index + 3))
    return (original_date + max(offset, 1))
}

#generate_new_date(visits$visit_index[1], visits$first_visit_date[1], visits$user_id[1])
generated_visits <- pmap(list(visits$visit_index,
                              visits$first_visit_date,
                              visits$user_id),
                         function(x, y, z) generate_new_date(x, y, z))

# pmap is losing the "date" and is returning a number, so we have to convert back; not sure this is the best way
generated_visits <- unlist(generated_visits)
visits$visit_date <- as.Date(generated_visits, origin = Sys.Date() - as.numeric(Sys.Date()))

visits <- visits %>%
    select(user_id, visit_date) %>%
    arrange(user_id, visit_date)

stopifnot(nrow(visits) == length(ids))

# some of the dates generated will be the same. BUT, that could represent multiple different pages in the same day
# so let's add path before we remove duplicates
```

```{r simulate_paths}
# duplicate home-page (example.com) to simulate many more home page visits than other pages
paths <- c('example.com', 'example.com', 'example.com/pricing', 'example.com/features')
#set.seed(42)
path_index <- ceiling(runif(nrow(visits), min=0, max=4))
visits$path <- map_chr(path_index, ~ paths[.])

# some of the dates generated will be the same. BUT, that could represent multiple different pages in the same day
# so let's add path before we remove duplicates
visits <- distinct(visits)
nrow(visits)

visits %>%
    count(path) %>%
    ggplot(aes(x=path, y=n)) +
    geom_col() +
    labs(title='Total Visits (day/user) single row represents >=1 visits for that day/user/path')

visits %>%
    group_by(user_id) %>%
    summarise(t=sd(as.numeric(visit_date))) %>%
    ggplot(aes(x=t)) +
        geom_histogram() +
        labs(title='Distribution of Number of Days between Visits')

temp <- inner_join(
    visits %>% 
        group_by(user_id) %>%
        summarise(first_visit_date=min(visit_date)) %>%
        count(first_visit_date) %>%
        rename(date=first_visit_date,
               new_users=n),
    visits %>%
        group_by(visit_date) %>%
        summarise(all_users=n()) %>%
        rename(date=visit_date),
    by='date')

temp %>% 
    gather(user_type, num_users, -date) %>%
    ggplot(aes(x=date, y=num_users, color=user_type)) +
        geom_line()

# visits %>%
#     group_by(user_id) %>%
#     filter(length(visit_date) != length(unique(visit_date))) %>%  # which users have a different number of unique dates fromf total dates
#     ungroup()

visits %>%
    count(visit_date, path) %>%
    ggplot(aes(x=visit_date, y=n, color=path)) +
    geom_line() +
    labs(title='Visits (per day/user) i.e. single row represents >=1 visits for that day/user/path')

prior_data <- visits
```

```{r simulate_metrics_experiments}
# experiment names
experiment_names <- c("Experiment 1", "Experiment 2", "Experiment Sim Currently Running")
# names of the metrics/conversions to track
metrics_names <- c('Sign Up', 'Use Feature 1', 'Talk to Sales', 'Pay/Subscribe')
# allowed number of days between seeing the experiment and giving credit for a conversion
# e.g. signup should happen quick, but we may want to give people more time to subscribe/pay for the service,
# since people want to try out the features before they decide to pay (e.g. if the service offers a trial or freemium)
attribution_windows_days <- c(2, 3, 5, 7)
historical_conversion_rates <- c(0.3, 0.2, 0.1, 0.08)
# conversion_rates contain the conversion rates of each metric for the A & B groups


experiments_metrics <- data.frame(metric_id=metrics_names, attribution_windows=attribution_windows_days)
experiments_metrics <- expand.grid(experiment_id=experiment_names, metric_id=experiments_metrics$metric_id) %>%
    inner_join(experiments_metrics, by = 'metric_id') %>%
    arrange(experiment_id, attribution_windows)

experiments_metrics
```

```{r simulate_experiment_traffic_1}
# for each experiment, we want to simulate, from the current visits/traffic dataset, who saw the experiment, on which page, and which variation

get_random_variation <- function(variation_names, user_id) {
    #set.seed(user_id)
    return (variation_names[rbinom(1, 1, 0.5) + 1])
}
#get_random_variation(variation_names, user_id=1)

create_experiment_visits <- function(start_date, end_date, experiment_paths, experiment_id, variation_names) {
    experiment_visits <- visits %>%
        group_by(user_id) %>%
        mutate(visit_index=rank(visit_date, ties.method = "first")) %>%
        ungroup() %>%
        mutate(new_user = ifelse(visit_index == 1, TRUE, FALSE)) %>%
        filter(visit_date >= start_date & visit_date <= end_date & path %in% experiment_paths) %>%
        select(-visit_index)
    
    expected_num_users <- length(unique(experiment_visits$user_id))
    
    experiment_visits <- experiment_visits %>%
        group_by(user_id) %>%
        mutate(visit_index=rank(visit_date, ties.method = "first")) %>%
        ungroup() %>%
        filter(visit_index == 1) %>%
        select(-visit_index) %>%
        rename(first_joined_experiment=visit_date) %>%
        mutate(experiment_id=experiment_id)
    experiment_visits$variation <- map_chr(experiment_visits$user_id, ~ get_random_variation(variation_names, .))
    
    stopifnot(nrow(experiment_visits) == expected_num_users)
    # make sure no duplicated user_ids
    stopifnot(nrow(experiment_visits) == length(unique(experiment_visits$user_id)))
    
    print(experiment_visits %>%
        count(variation) %>%
        ggplot(aes(x=variation, y=n)) +
        geom_col())
    
    print(experiment_visits %>%
        count(first_joined_experiment) %>%
        ggplot(aes(x=first_joined_experiment, y=n)) +
        geom_line() +
        labs(title='Number of People Entering Experiment'))
    
    print(experiment_visits %>%
        count(first_joined_experiment, new_user) %>%
        ggplot(aes(x=first_joined_experiment, y=n, color=new_user)) +
        geom_line() +
        labs(title='Number of People Entering Experiment, shows affect of including new returning users in experiment'))
    
    print(experiment_visits %>%
        count(first_joined_experiment, variation) %>%
        ggplot(aes(x=first_joined_experiment, y=n, color=variation)) +
        geom_line())
    
    return (experiment_visits %>% select(-new_user))

}

#### Experiment 1

# let's start the experiment 2 months after our visits dataset, and run it for a month
start_date <- min(visits$visit_date) + 60
end_date <- start_date + 30 # 
# all paths
experiment_paths <- unique(paths)
# experiment 1
variation_names <- c("original", "variant")
experiment_id <- experiment_names[1]
experiment_visits_1 <- create_experiment_visits(start_date, end_date, experiment_paths, experiment_id, variation_names)
experiment_visits_1
```

```{r simulate_experiment_traffic_2}
#### Experiment 2
start_date <- min(visits$visit_date) + 75
end_date <- start_date + 30 # 
# all paths
experiment_paths <- paths[4] # just features page
# experiment 1
variation_names <- c("A", "B")
experiment_id <- experiment_names[2]
experiment_visits_2 <- create_experiment_visits(start_date, end_date, experiment_paths, experiment_id, variation_names)
experiment_visits_2
```

```{r simulate_experiment_traffic_currently_running}
#### Experiment 2
start_date <- Sys.Date() - 5
end_date <- start_date + 30 # 
# all paths
experiment_paths <- paths[1] # just homepage
# experiment 1
variation_names <- c("A", "B")
experiment_id <- experiment_names[length(experiment_names)]
experiment_visits_currently_running <- create_experiment_visits(start_date, end_date, experiment_paths, experiment_id, variation_names)
experiment_visits_currently_running
```

```{r experiments}
experiments_all <- rbind(experiment_visits_1,
                         experiment_visits_2,
                         experiment_visits_currently_running) %>%
    select(user_id, experiment_id, variation, first_joined_experiment, path) %>%
    arrange(user_id, experiment_id)

# ensure dataset is unique by user-id/experiment-id
stopifnot(nrow(distinct(experiments_all %>% select(user_id, experiment_id))) == nrow(experiments_all))

experiments_all
```

```{r adjust_crs}
# we want to adjust conversion rates for the people who were part of certain experiments
# such that the A/B groups have different conversion rates 
# some will have different CRs due to random noise, some will have differences in probability distributions
# i.e. true differences.


adjusted_conversion_rates <- inner_join(experiments_metrics,
                                        data.frame(metric_id=metrics_names, historical_conversion_rate=historical_conversion_rates),
                                        by = "metric_id") %>%
    select(-attribution_windows) %>%
    mutate(index=row_number())

# Experiment 1 has positive conversion rates, # we'll assum
adjusted_conversion_rates <- inner_join(adjusted_conversion_rates,
                                        expand.grid(index=adjusted_conversion_rates$index, variation=c('A', 'B')),
                                        by="index") %>%
    select(experiment_id, variation, metric_id, historical_conversion_rate)

adjusted_conversion_rates$adjusted_conversion_rate <- adjusted_conversion_rates$historical_conversion_rate

percent_change_adjustments <- c(
                    NA, # Experiment 1                        A   Sign Up
                    0.10, # Experiment 1                        B   Sign Up
                    NA, # Experiment 1                        A   Use Feature 1  
                    0.07, # Experiment 1                        B   Use Feature 1  
                    NA, # Experiment 1                        A   Talk to Sales  
                    NA, # Experiment 1                        B   Talk to Sales  
                    NA, # Experiment 1                        A   Pay/Subscribe  
                    0.05, # Experiment 1                        B   Pay/Subscribe  
                    NA, # Experiment 2                        A   Sign Up
                    -0.10, # Experiment 2                        B   Sign Up
                    NA, # Experiment 2                        A   Use Feature 1  
                    -0.07, # Experiment 2                        B   Use Feature 1  
                    NA, # Experiment 2                        A   Talk to Sales  
                    -0.05, # Experiment 2                        B   Talk to Sales  
                    NA, # Experiment 2                        A   Pay/Subscribe  
                    0.03, # Experiment 2                        B   Pay/Subscribe  
                    NA, # Experiment Sim Currently Running    A   Sign Up
                    0.10, # Experiment Sim Currently Running    B   Sign Up
                    NA, # Experiment Sim Currently Running    A   Use Feature 1  
                    0.07, # Experiment Sim Currently Running    B   Use Feature 1  
                    NA, # Experiment Sim Currently Running    A   Talk to Sales  
                    0.05, # Experiment Sim Currently Running    B   Talk to Sales  
                    NA, # Experiment Sim Currently Running    A   Pay/Subscribe  
                    0.05) # Experiment Sim Currently Running    B   Pay/Subscribe  
            

adjusted_conversion_rates <- adjusted_conversion_rates %>%
    mutate(adjusted_conversion_rate=ifelse(is.na(percent_change_adjustments),
                                           historical_conversion_rate,
                                           (percent_change_adjustments * historical_conversion_rate) + historical_conversion_rate))

# Experiment 1 has c("original", "variant") rather than A/B
temp_names <- c("original", "variant")
adjusted_conversion_rates <- adjusted_conversion_rates %>%
    mutate(variation = as.character(variation),
           variation = ifelse(experiment_id == experiment_names[1],
                              ifelse(variation == 'A', temp_names[1], temp_names[2]),
                              variation))
adjusted_conversion_rates
```

```{r conversion_rates_for_id_experiment_metric}
# now we want to determine the conversion rates for each person, based on experiment, metric_id, variation, so we can binom distribution based on the conversion rate
# if the person isn't part of an experiment, then we will use the historical conversion rate
names(historical_conversion_rates) <- metrics_names
# historical_conversion_rates[metrics_names[1]]

# create a dateframe that has a historical conversion rate for each user/metric combo
user_metric_crs <- expand.grid(user_id=unique(visits$user_id), metric_id=metrics_names) %>%
    arrange(user_id, metric_id) %>%
    mutate(historical_conversion_rate=historical_conversion_rates[metric_id])

# now add experiment/variation columns for users that were part of experiments
user_metric_crs <- full_join(user_metric_crs,
          experiments_all %>% select(user_id, experiment_id, variation), by='user_id')

# based on experiment/variation/metric, get the chosen conversion rate
user_metric_crs <- left_join(user_metric_crs %>% 
              mutate(metric_id = as.character(metric_id)),
          adjusted_conversion_rates %>%
              select(-historical_conversion_rate) %>%
              mutate(experiment_id = as.character(experiment_id),
                     metric_id = as.character(metric_id)),
          by=c('experiment_id', 'variation', 'metric_id')) %>%
    mutate(conversion_rate=ifelse(is.na(adjusted_conversion_rate), historical_conversion_rate, adjusted_conversion_rate)) %>%
    select(user_id, metric_id, conversion_rate)


# some people will have partipated in multiple experiments, so we'll take the average to get a dataset that is unique per user/metric
user_metric_crs <- user_metric_crs %>% 
    group_by(user_id, metric_id) %>%
    summarise(conversion_rate = mean(conversion_rate)) %>%
    ungroup()

stopifnot(length(unique(user_metric_crs$user_id)) == length(unique(visits$user_id)))

# now we will determine if each person convertes based on their conversion rate using the binomial distribution

#rbinom(1000, 1, 0.08)

simulate_conversion <- function(user_id, conversion_rate) {
    ##set.seed(user_id+10)
    return (rbinom(1, 1, conversion_rate))
}

# now we simulating them converting or not by using their assigned conversion rates as a probability in a binom distribution
user_metric_crs$converted <- as.logical(map2_dbl(user_metric_crs$user_id,
                    user_metric_crs$conversion_rate, 
                    ~ simulate_conversion(.x, .y)))

user_metric_crs %>%
    count(metric_id, converted) %>%
    mutate(n = n / length(unique(user_metric_crs$user_id))) %>%
    ggplot(aes(x=metric_id, y=n, group=converted, fill=converted)) +
    geom_col(position='dodge') +
    geom_text(aes(label=percent(n)))

conversion_data <- inner_join(user_metric_crs %>%
                                  filter(converted) %>%
                                  select(user_id, metric_id),
                              visits %>% 
                                  group_by(user_id) %>%
                                  summarise(first_visit=min(visit_date)),
                              by='user_id')


temp <- inner_join(
    inner_join(experiments_all, conversion_data, by='user_id') %>%
        mutate(converted=!is.na(first_joined_experiment)) %>%
        count(experiment_id, variation, metric_id),
    experiments_all %>% count(experiment_id, variation),
    by=c('experiment_id', 'variation'))
temp %>%
    mutate(cr=n.x/n.y) %>%
    arrange(experiment_id, metric_id, variation) %>%
    mutate(metric_id=factor(metric_id, levels=metrics_names)) %>%
    ggplot(aes(x=metric_id, y=cr, group=variation, fill=variation)) +
    geom_col(position='dodge') +
    facet_wrap(~ experiment_id) +
    geom_text(aes(label=round(cr, 3)),
              position = position_dodge(width = 1), 
              size=3) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r}
generate_offset <- function(user_id, metric) {
 
    # NOTE setting the seed is messing up the distribution   
    ##  set.seed(user_id)
    rbinom(1, 30, attribution_windows_days[metric]/30)
}

names(attribution_windows_days) <- metrics_names
conversion_offsets <- map2_dbl(conversion_data$user_id, 
                               conversion_data$metric_id,
                               #~ rbinom(1, 30, attribution_windows_days[.y]/30))
                               ~ generate_offset(.x, .y))
conversion_data <- conversion_data %>%
    mutate(offset=conversion_offsets,
           conversion_date = first_visit + offset)

conversion_data %>%
    count(metric_id, offset) %>%
    mutate(offset=factor(offset)) %>%
    mutate(metric_id=fct_reorder(metric_id, n, .desc = TRUE)) %>%
    ggplot(aes(x=offset, y=n)) +
        geom_col() +
    facet_wrap( ~ metric_id, scales = 'free_y') +
    labs(title='Distribution of Days from First Visit to Event Conversion, for those that convert')

conversion_data %>%
    count(conversion_date, metric_id) %>%
    ggplot(aes(x=conversion_date, y=n)) +
        geom_line() +
    facet_wrap( ~ metric_id, scales = 'free_y') +
    labs(title='Daily Conversions')

conversion_data <- conversion_data %>%
    select(user_id, metric_id, conversion_date) %>%
    arrange(user_id, conversion_date)

conversion_data
```

```{r save_simulated_data}
write.csv(experiments_metrics, file='../shiny-app/simulated_data/attribution_windows.csv', row.names = FALSE)
write.csv(prior_data, file='../shiny-app/simulated_data/website_traffic.csv', row.names = FALSE)
write.csv(experiments_all, file='../shiny-app/simulated_data/experiment_traffic.csv', row.names = FALSE)
write.csv(conversion_data, file='../shiny-app/simulated_data/conversion_rate_data.csv', row.names = FALSE)
```


```{r eval=FALSE, include=FALSE}
#seeds <- 0:1000
seeds <- 1000:2000
#seeds <- signup_conversions$user_id
# temp <- function(seed, use_seeds) {
#     if(use_seeds) {
##         set.seed(seed)    
#     }
#     rbinom(1, 30, 3/30)
# }
temp <- function(seed, use_seeds) {
    if(use_seeds) {
        #set.seed(seed)    
    }
    max(round(rnorm(1, 3, 2)), 0)
}
hist(map_dbl(seeds, ~ temp(., TRUE)))
hist(map_dbl(seeds, ~ temp(., FALSE)))
```


# historical traffic

```{r eval=FALSE, include=FALSE}
website_traffic <- prior_data


create_cohort <- function(date_object, cohort_method=month, pad_width=2) {

    return (
        paste0(year(date_object),
               '-',
               str_pad(cohort_method(date_object), width=pad_width, side='left', pad = '0'))
    )
}

#######
show_path <- TRUE
top_x_paths <- 2
start_date <- Sys.Date() - 270
end_date <- Sys.Date() - 30

cohort_type <- month
######

visitors_per_day_per_path <- website_traffic %>%
    filter(visit_date >= start_date & visit_date <= end_date) %>%
    group_by(user_id) %>%
    mutate(visit_index=rank(visit_date, ties.method = "first")) %>%
    ungroup() %>%
    mutate(date = factor(create_cohort(visit_date)),
           path= fct_lump(path,  n=top_x_paths),
           visit_type = ifelse(visit_index == 1, 'New', 'Returning'))
    
if(show_path) {

    visitors_per_day_per_path %>%
        count(date, path, visit_type) %>%
        ggplot(aes(x=date, y=n, color=path, group=path)) +
            geom_line() +
            geom_point() + 
            facet_grid(visit_type ~ .) + 
            scale_y_continuous(labels = comma_format()) +
            geom_text(aes(label=n), vjust=-1, size=3, check_overlap=TRUE) +    
            theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
            labs(title='Website Visitors',
                 y='Number of Visits',
                 x='Month',
                 color='Path')
} else {

    visitors_per_day_per_path %>%
        count(date, visit_type) %>%
        ggplot(aes(x=date, y=n, color=visit_type, group=visit_type)) +
            geom_line() +
            geom_point() + 
            expand_limits(y=0) +
            scale_y_continuous(labels = comma_format()) +
            geom_text(aes(label=n), vjust=-1, size=3, check_overlap=TRUE) +
            theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
            labs(title='Website Visitors',
                 y='Number of Visits',
                 x='Month',
                 color='Visitor Type')
}
```

```{r eval=FALSE, include=FALSE}
experiment_start_stop <- experiments_all %>%
    group_by(experiment_id) %>%
    summarise(start=min(first_joined_experiment),
              end=max(first_joined_experiment)) %>%
    arrange(desc(start))
    
experiments <- unique(experiment_start_stop$experiment_id)

experiments[1]



experiment_name <- 'Experiment 1'
metrics <- (experiments_metrics %>% 
    filter(experiment_id == experiment_name))$metric_id



experiments_all %>%
    count(experiment_id, path) %>%
    arrange(experiment_id, desc(n)) %>%
    rename(visits = n)
```

```{r}
experiments_metrics <- experiments_metrics %>%
    mutate_if(is.factor, as.character) 

experiment_name <- 'Experiment 1'

#experiments_all %>% count(experiment_id, variation)
#temp <- experiments_all %>% filter(experiment_id == experiment_names[1], variation == 'original') 
#any(temp$user_id %in% conversion_data$user_id)

# dataset only contains users that converted
user_conversion_rates <-  experiments_all %>% 
    filter(experiment_id == experiment_name) %>%
    #select(user_id, variation, first_joined_experiment, path) %>%
    inner_join(conversion_data, by='user_id') %>%
    #left_join()
    arrange(user_id) %>%
    left_join(experiments_metrics, by=c('experiment_id', 'metric_id')) %>%
    mutate(days_from_experiment_to_conversion = as.numeric(difftime(conversion_date,  # negative days means the conversion happened before the experiment started
                                                                    first_joined_experiment,
                                                                    units = 'days')),
           converted_within_window = days_from_experiment_to_conversion >= 0 & days_from_experiment_to_conversion <= attribution_windows)

stopifnot(!any(is.na(user_conversion_rates)))


temp_conversions_ignore_window <- user_conversion_rates %>% count(variation, metric_id)


# we have to filter out anyone that who first joined the experiment in the last x days, where x is less than the attribution window for that metric
users_to_filter_out <- (user_conversion_rates %>%
    filter(first_joined_experiment >= Sys.Date() - attribution_windows))$user_id

user_conversion_rates <- user_conversion_rates %>%
    filter(! user_id %in% users_to_filter_out)


# this dataset contains all the conversions, but some will not have converted within the time window; we still want to keep them for now to analyze how many converted before/during/after the experiment/window
user_conversion_rates <- user_conversion_rates %>%
    select(-experiment_id, -first_joined_experiment, -attribution_windows)

experiment_summary <- user_conversion_rates %>%
    filter(converted_within_window) %>%
    count(variation, metric_id) %>%
    rename(converted=n)

total_users <- experiments_all %>%
    filter(experiment_id == experiment_name,
           ! user_id %in% users_to_filter_out) %>%
    group_by(variation) %>%
    summarise(num_users=n(),
              num_distinct_users=n_distinct(user_id),
              same=num_users == num_distinct_users)
stopifnot(all(total_users$same))

experiment_summary <- inner_join(total_users, experiment_summary, by='variation') %>%
    select(variation, metric_id, converted, num_users) %>%
    mutate(conversion_rate=converted / num_users)

experiment_summary <- experiment_summary %>%
    gather(variable, value, -(variation:metric_id)) %>%
    unite(temp, variation, variable) %>%
    spread(temp, value) %>%
    arrange(desc(original_conversion_rate))

experiment_summary$p_value <- pmap_dbl(list(experiment_summary$original_converted, experiment_summary$variant_converted, experiment_summary$original_num_users, experiment_summary$variant_num_users),
         function(a, b, x, y) round(prop.test(x=c(a, b), n=c(x, y))$p.value, 3))

experiment_summary <- experiment_summary %>%
    mutate(percent_change = (variant_conversion_rate - original_conversion_rate) / original_conversion_rate) %>%
    select(metric_id, percent_change, p_value, everything())

experiment_summary

experiment_summary %>%
    select(metric_id, original_conversion_rate, variant_conversion_rate) %>%
    gather(type, cr, -metric_id) %>%
    mutate(metric_id = factor(metric_id, levels=metrics_names)) %>%
    ggplot(aes(x=metric_id, y=cr, group=type, fill=type)) +
        geom_col(position='dodge') +
        geom_text(aes(label=round(cr, 3)),
                  position = position_dodge(width = 1), 
                  size=3) +
        theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
        labs(title='Conversion rates (accounts for time windows)')


inner_join(temp_conversions_ignore_window,
    total_users, by='variation') %>%
    mutate(cr=n/num_users) %>%
    mutate(metric_id = factor(metric_id, levels=metrics_names)) %>%
    ggplot(aes(x=metric_id, y=cr, group=variation, fill=variation)) +
        geom_col(position='dodge') +
        geom_text(aes(label=round(cr, 3)),
                  position = position_dodge(width = 1), 
                  size=3) +
        theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
        labs(title='Conversion rates (ignores the time windows)')


experiment_summary
```

```{r}
prior_days <- 15


experiment_start_stop <- experiments_all %>%
    group_by(experiment_id) %>%
    summarise(start=min(first_joined_experiment),
              end=max(first_joined_experiment)) %>%
    arrange(desc(start))


max_attribution_window <- max((experiments_metrics %>%
    filter(experiment_id == experiment_name))$attribution_windows)


experiment_paths <- unique((experiments_all %>% filter(experiment_id == experiment_name))$path)
start_stop <- experiment_start_stop %>% filter(experiment_id == experiment_name)
experiment_start_date <- start_stop$start

prior_start_date <- experiment_start_date - prior_days - max_attribution_window
prior_end_date <- experiment_start_date - max_attribution_window




prior_history <- visits %>%
    filter(path %in% experiment_paths,
           visit_date >= prior_start_date & visit_date <= prior_end_date) %>%   # give extra days to allow for attribution window
    group_by(user_id) %>%
    summarise(first_prior_visit = min(visit_date))

prior_conversion_rates <- inner_join(conversion_data, prior_history, by='user_id')
prior_conversion_rates <- inner_join(prior_conversion_rates,
           experiments_metrics %>%
               filter(experiment_id == experiment_name) %>%
               select(-experiment_id),
           by='metric_id')


prior_conversion_rates <- prior_conversion_rates %>%
    mutate(days_from_prior_visit_to_conversion = as.numeric(difftime(conversion_date,  # negative days means the conversion happened before the experiment started
                                                                    first_prior_visit,
                                                                    units = 'days')),
           converted_within_window = days_from_prior_visit_to_conversion >= 0 & days_from_prior_visit_to_conversion <= attribution_windows) %>%
    filter(converted_within_window)

prior_summary <- prior_conversion_rates %>%
    count(metric_id) %>%
    mutate(total = length(prior_history$user_id),
           conversion_rate = n / total) %>%
    rename(successes=n,
           trials=total) %>%
    mutate(alpha=successes,
           beta=trials-successes)


prior_summary %>%
    mutate(metric_id = factor(metric_id, levels=metrics_names)) %>%
    ggplot(aes(x=metric_id, y=conversion_rate)) +
        geom_col() +
        geom_text(aes(label=round(conversion_rate, 3)), vjust=-0.5)
    

#prior_distributions
prior_alpha <- 464
prior_beta <- 2863 - 464

new_alpha_a <- prior_alpha + 445
new_beta_a <- prior_beta + (2555 - 445)

new_alpha_b <- prior_alpha + 506
new_beta_b <- prior_beta + (2507 - 506)

experiment_summary
summary
x <- seq(0, 1, 0.001)
temp <- data.frame(x,
                   prior=dbeta(x, prior_alpha, prior_beta),
                   a=dbeta(x, new_alpha_a, new_beta_a),
                   b=dbeta(x, new_alpha_b, new_beta_b)) %>%
    gather(type, value, -x)

prior_summary
a_cr_simulation <- rbeta(1e6, new_alpha_a, new_beta_a)
b_cr_simulation <- rbeta(1e6, new_alpha_b, new_beta_b)
percent_of_time_b_wins <- mean(b_cr_simulation > a_cr_simulation)


temp %>%
    ggplot(aes(x, value, group=type, color=type)) +
    geom_line() +
    geom_vline(xintercept = 895 / 5009) +
    coord_cartesian(x=c(0.15, 0.25))

percent_of_time_b_wins



# we want a daily count of successes & trails, for both variations, per metric, considering only the people who have 
# allowed enough time for the time windows (i.e. the entered the experiment more than x days prior from the relative point/day in time, where x is the attribution window for the metric)
#
daily_totals_per_variation <- experiments_all %>% 
    filter(experiment_id == experiment_name) %>%
    count(first_joined_experiment, variation) %>%
    arrange(first_joined_experiment, variation)


experiments_current <- experiments_all %>% filter(experiment_id == experiment_name)
attribution_windows_current <- experiments_metrics %>% filter(experiment_id == experiment_name)

experiment_start_date
experiment_end_date <- (start_stop %>% filter(experiment_id == experiment_name))$end

experiment_day <- seq(experiment_start_date, experiment_end_date, 1)

temp <- expand.grid(user_id=experiments_current$user_id,
            metric_id=(experiments_metrics %>% filter(experiment_id == experiment_name))$metric_id) %>%
    inner_join(experiments_current, by='user_id') %>%
    inner_join(experiments_metrics, by=c('experiment_id', 'metric_id')) %>%
    mutate(expired_time_window=first_joined_experiment + attribution_windows)
    
cumulative_conversions <- left_join(temp %>% select(user_id, variation, metric_id, expired_time_window),
          user_conversion_rates %>% select(user_id, variation, metric_id, converted_within_window) %>% filter(converted_within_window),
          by=c('user_id', 'variation', 'metric_id')) %>%
    mutate(converted_within_window=ifelse(is.na(converted_within_window), FALSE, converted_within_window)) %>%
    group_by(expired_time_window, variation, metric_id) %>%
    summarise(successes=sum(converted_within_window),
              trials=n()) %>% 
    ungroup() %>%
    arrange(expired_time_window, variation, metric_id) %>%
    group_by(variation, metric_id) %>%
    mutate(cumulative_successes=cumsum(successes),
           cumulative_trials=cumsum(trials)) %>%
    ungroup()

cumulative_conversions %>%
    filter(metric_id == 'Sign Up') %>%
    select(-successes, -trials) %>%
    gather(type, value, -expired_time_window, -variation, -metric_id) %>%
    ggplot(aes(x=expired_time_window, y=value, group=type, color=type)) +
    geom_line() +
    facet_wrap(~variation) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
    labs(title='Success/Trials over time - Signups')


cumulative_conversions %>%
    filter(metric_id == 'Talk to Sales') %>%
    select(-successes, -trials) %>%
    gather(type, value, -expired_time_window, -variation, -metric_id) %>%
    ggplot(aes(x=expired_time_window, y=value, group=type, color=type)) +
    geom_line() +
    facet_wrap(~variation) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
    labs(title='Success/Trials over time - Talk to Sales')


variation_names <- sort(unique(cumulative_conversions$variation))
variation_a <- variation_names[1]
variation_b <- variation_names[2]

temp <- inner_join(cumulative_conversions %>% select(-successes, -trials),
           prior_summary %>% select(metric_id, alpha, beta) %>% rename(prior_alpha=alpha, prior_beta=beta),
           by='metric_id') %>%
    mutate(new_alpha = prior_alpha + cumulative_successes,
           new_beta = prior_beta + (cumulative_trials - cumulative_successes))


simulate_b_wins <- function(alpha_a, beta_a, alpha_b, beta_b, number_of_draws=1e6) {
    
    a_cr_simulation <- rbeta(number_of_draws, alpha_a, beta_a)
    b_cr_simulation <- rbeta(number_of_draws, alpha_b, beta_b)
    
    return ( mean(b_cr_simulation > a_cr_simulation) )
}
    
prob_over_time <- temp %>%
    group_by(expired_time_window, metric_id) %>%
    summarise(prob_b_better_a=simulate_b_wins(alpha_a=new_alpha[variation == variation_a],
                                              beta_a=new_beta[variation == variation_a],
                                              alpha_b=new_alpha[variation == variation_b],
                                              beta_b=new_beta[variation == variation_b],
                                              number_of_draws=1e4)) %>%
    arrange(expired_time_window, metric_id)
prob_over_time %>%
    ggplot(aes(x=expired_time_window, y=prob_b_better_a, group=metric_id, color=metric_id)) +
    geom_line(alpha=0.5) +
#    geom_smooth(method='loess', se=FALSE) +
    expand_limits(y=0)


credible_interval_approx <- function(alpha_a, beta_a, alpha_b, beta_b) {
# https://github.com/dgrtwo/empirical-bayes-book/blob/master/bayesian-ab.Rmd
    u1 <- alpha_a / (alpha_a + beta_a)
    u2 <- alpha_b / (alpha_b + beta_b)
    var1 <- alpha_a * beta_a / ((alpha_a + beta_a) ^ 2 * (alpha_a + beta_a + 1))
    var2 <- alpha_b * beta_b / ((alpha_b + beta_b) ^ 2 * (alpha_b + beta_b + 1))
    
    mu_diff <- u2 - u1
    sd_diff <- sqrt(var1 + var2)
    
    # in D.R. code, the first player had a higher probability but a negative estimate (i.e. negative difference in conversion rate, mu_diff)
    # This doesn't make sense, so we'll 1) use the first player as the A group and the second as the B group), so B-A 
    # which gives the expected intervals (but flips the posterior probability), and 2) use 1-pnorm(...) to get the correct posterior probability
    c(posterior = 1 - pnorm(0, mu_diff, sd_diff),
            cr_diff_estimate = mu_diff,
            conf.low = qnorm(.025, mu_diff, sd_diff),
            conf.high = qnorm(.975, mu_diff, sd_diff))
}

temp_credible_interval <- temp %>%
    group_by(expired_time_window, metric_id) %>%
    summarise(asdf=list(credible_interval_approx(alpha_a=new_alpha[variation == variation_a],
                                       beta_a=new_beta[variation == variation_a],
                                       alpha_b=new_alpha[variation == variation_b],
                                       beta_b=new_beta[variation == variation_b]))) %>%
    ungroup()

credible_intervals <- cbind(temp_credible_interval, as.data.frame(do.call("rbind", temp_credible_interval$asdf))) %>%
    select(expired_time_window, metric_id, posterior, cr_diff_estimate, conf.low, conf.high) %>%
    arrange(expired_time_window, metric_id)


credible_interval_approx(alpha_a=3872,
                         beta_a=8880,
                        alpha_b=2228,
                         beta_b=5071
                         )
qnorm(0.5, mu_diff, sd_diff)


credible_intervals %>%
    ggplot(aes(x=expired_time_window, y=cr_diff_estimate)) +
        geom_line() +
        geom_hline(yintercept = 0, color='red') +
        geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.2) +
        facet_wrap(~metric_id)

credible_intervals %>%
    ggplot(aes(x=expired_time_window, y=cr_diff_estimate)) +
        geom_line() +
        #     geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.2) +
        geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = 'green', alpha=0.1) +
        geom_ribbon(aes(ymin = ifelse(conf.low <= 0, conf.low, NA), ymax = ifelse(conf.low <= 0, conf.high, NA)), fill = 'red', alpha=0.35) +
        geom_ribbon(aes(ymin = ifelse(conf.low > 0, conf.low, NA), ymax = ifelse(conf.low > 0, conf.high, NA)), fill = 'green', alpha=0.2) +
        geom_hline(yintercept = 0, color='red', alpha=0.5) +
        facet_wrap(~metric_id)
```


```{r}
p_values <- function(successes_a, trials_a, successes_b, trials_b) {
    
    test_results <- prop.test(x=c(successes_b, successes_a), n=c(trials_b, trials_a))
    return (c(p_value = test_results$p.value,
              cr_diff_estimate = as.numeric(test_results$estimate[1] - test_results$estimate[2]),
              conf.low = test_results$conf.int[1],
              conf.high = test_results$conf.int[2]))
}

# 
# 
# test_results <- prop.test(x=c(3872, 2228), n=c((3872+8880), (2228+5071)))
# test_results$p.value
# test_results$conf.int[1]
# test_results$conf.int[2]
# 
# p_values(3872, 3872+8880, 2228, 2228+5071)

temp_p_value <- temp %>%
    group_by(expired_time_window, metric_id) %>%
    summarise(asdf=list(p_values(successes_a=cumulative_successes[variation == variation_a],
                                 trials_a=cumulative_trials[variation == variation_a],
                                 successes_b=cumulative_successes[variation == variation_b],
                                 trials_b=cumulative_trials[variation == variation_b]))) %>%
    ungroup()

p_value_intervals <- cbind(temp_p_value, as.data.frame(do.call("rbind", temp_p_value$asdf))) %>%
    select(expired_time_window, metric_id, p_value, cr_diff_estimate, conf.low, conf.high) %>%
    arrange(expired_time_window, metric_id)

p_value_intervals %>%
    group_by(metric_id) %>%
    mutate(visit_index=rank(-as.numeric(expired_time_window), ties.method = "first")) %>%
    ungroup() %>%
    ggplot(aes(x=expired_time_window, y=p_value)) +
        geom_hline(yintercept = 0.05, color='red', alpha=0.5) +
        geom_line(aes(group=metric_id, color = ifelse(p_value <= 0.05, 'green', 'red'))) +
    #geom_line(aes(col=ifelse(p_value <= 0.05, 'green', 'red'))) +
        #geom_line() +
        scale_colour_manual(values=c(green="green",red="red")) +
        geom_text(aes(label=ifelse(visit_index == 1, round(p_value, 3), '')), vjust=-1) +
        facet_wrap(~metric_id) +
        labs(title='P-value over time i.e. cumuatlive successes/trails') +
        theme(legend.position = 'none')
        

p_value_intervals %>%
    group_by(metric_id) %>%
    mutate(visit_index=rank(-as.numeric(expired_time_window), ties.method = "first")) %>%
    ungroup() %>%
    mutate(group=conf.low > 0) %>%
    ggplot(aes(x=expired_time_window, y=cr_diff_estimate)) +
        geom_hline(yintercept = 0, color='red', alpha=0.5) +
        geom_line() +
        geom_ribbon(aes(ymax = 0, ymin = ifelse(conf.low >= 0, 0, conf.low)), fill = 'red', alpha=0.3) +
        geom_ribbon(aes(ymin = ifelse(conf.low >= 0, conf.low, 0), ymax = ifelse(conf.high <= 0, 0, conf.high)), fill = 'green', alpha=0.3) +
        geom_text(aes(label=ifelse(visit_index == 1, percent(cr_diff_estimate), '')), vjust=-1) +
        facet_wrap(~metric_id) +
        labs(title='Freq. prop.test conf interval') #+
        #scale_fill_manual(values=c(green="green",red="red")) +
        #theme(legend.position = 'none')


p_value_intervals %>%
    group_by(metric_id) %>%
    mutate(visit_index=rank(-as.numeric(expired_time_window), ties.method = "first")) %>%
    ungroup() %>%
    mutate(group=conf.low > 0) %>%
    ggplot(aes(x=expired_time_window, y=cr_diff_estimate)) +
        geom_line() +
        # ribbon if conf.low is above 0
        geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = 'green', alpha=0.15) +
        geom_ribbon(aes(ymin = ifelse(conf.low <= 0, conf.low, NA), ymax = ifelse(conf.low <= 0, conf.high, NA)), fill = 'red', alpha=0.45) +
        geom_ribbon(aes(ymin = ifelse(conf.low > 0, conf.low, NA), ymax = ifelse(conf.low > 0, conf.high, NA)), fill = 'green', alpha=0.2) +
        geom_hline(yintercept = 0, color='red', alpha=0.5) +
        # geom_ribbon(aes(ymax = 0, ymin = ifelse(conf.low >= 0, 0, conf.low)), fill = 'red', alpha=0.3) +
        # geom_ribbon(aes(ymin = ifelse(conf.low >= 0, conf.low, 0), ymax = ifelse(conf.high <= 0, 0, conf.high)), fill = 'green', alpha=0.3) +
        geom_text(aes(label=ifelse(visit_index == 1, percent(cr_diff_estimate), '')), vjust=-1) +
        facet_wrap(~metric_id) +
        labs(title='Freq. prop.test conf interval') #+
        #scale_fill_manual(values=c(green="green",red="red")) +
        #theme(legend.position = 'none')
 

p_value_intervals %>%
    filter(metric_id == 'Sign Up')

?geom_ribbon
experiment_summary
?geom_errorbarh
```


```{r}
temp %>%
    select(expired_time_window, variation, metric_id, cumulative_successes, cumulative_trials) %>%
    mutate(cr=cumulative_successes / cumulative_trials) %>%
    ggplot(aes(x=expired_time_window, y=cr, group=variation, color=variation)) +
        geom_line() +
        facet_wrap( ~ metric_id) + 
        expand_limits(y=0) +
        labs(title='Conversion Rates over time')


cia_list <- pmap(with(experiment_summary, list(original_converted, original_num_users, variant_converted, variant_num_users)),
                 function(a_success, a_trial, b_success, b_trial){
                     credible_interval_approx(alpha_a = a_success,
                                              beta_a = a_trial - a_success,
                                              alpha_b = b_success,
                                              beta_b = b_trial - b_success)
                 })

freq_list <- pmap(with(experiment_summary, list(original_converted, original_num_users, variant_converted, variant_num_users)),
                 function(a_success, a_trial, b_success, b_trial){
                     p_values(successes_a = a_success,
                              trials_a = a_trial,
                              successes_b = b_success,
                              trials_b = b_trial)
                 })



experiment_summary
temp_experiment_summary <- experiment_summary %>% 
    mutate(prob_b_is_better=map_dbl(cia_list, ~.['posterior']),
           bayesian_cr_diff_estimate=map_dbl(cia_list, ~.['cr_diff_estimate']),
           bayesian_conf.low=map_dbl(cia_list, ~.['conf.low']),
           bayesian_conf.high=map_dbl(cia_list, ~.['conf.high']),
           freq_p_value=map_dbl(freq_list, ~.['p_value']),
           freq_cr_diff_estimate=map_dbl(freq_list, ~.['cr_diff_estimate']),
           freq_conf.low=map_dbl(freq_list, ~.['conf.low']),
           freq_conf.high=map_dbl(freq_list, ~.['conf.high']))

#View(temp_experiment_summary)
experiment_summary <- temp_experiment_summary

```

```{r}
experiment_summary


```
























